spring:
  application:
    name: vehicle-catalog-service
  datasource:
    url: jdbc:postgresql://pk-ev-dev.postgres.database.azure.com:5432/vehicle_catalog
    username: postgres
    password: Password!23
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Redis Server Connection
  data:
   redis:
    host: pk-ev-dev.centralindia.redis.azure.net
    port: 10000
  # password: yourpassword (if applicable)

# JWT Configuration
jwt:
  secret-key: 8c326a98bdeef63921e69388cda2b0169a5aebea61801ef7fdef0c558334fdaa2081a99b5319598360591994e66796b8f2fbc602477d1d9c66a6f36fd7ab31863654e03bcd7bc60dc15e6aed4b66ab7cc50749b6f068ffaf288e5407efac1eb49ee886e9d86bac7b9e66f010200d641d1c032d5221fac57c26f4bc2046dd3dd5
  expiration-ms: 3600000

# Add custom properties for unauthenticated endpoints
security:
  unauthenticated-endpoints:
    - "/users/authenticate"
    - "/customers/register"
